---
- name: Ensure Greenbone working directory exists
  file:
    path: "/home/kaca/greenbone-docker"

    state: directory
    owner: kaca
    group: kaca

- name: Template Docker Compose file
  template:
    src: docker-compose.j2
    dest: "/home/kaca/greenbone-docker/docker-compose.yml"


- name: Deploy Greenbone via Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/home/kaca/greenbone-docker"

    state: present
